### ISSUE TITLE
panic: Config File "nfc" Not Found in "[/home/mj/go/src/nfCollector/configs]"

### ISSUE THREAD

**Issue by yaquaholic** [javadmohebbi/nfCollector#1]
Hi there, 

The installation went well until I checked if the service was running. but i can't get it to start.
When testing from the command line I am getting the following:

<Timestamp> Error reading config file, Config File "nfc" Not Found in "[/home/mj/go/src/nfCollector/configs]"
panic: Config File "nfc" Not Found in "[/home/mj/go/src/nfCollector/configs]"

Any ideas?

**Comment by yaquaholic** [comment]
I fixed this by creating /home/mj/go/src/nfCollector/configs/ and copying /etc/nfcol/nfc.yaml to the folder. I used the .deb installation method.

**Comment by javadmohebbi** [comment]
Hi Dear @yaquaholic

I've reproduced the mentioned problem. You are right, I forgot to make the dummy IsDev Variable to false. Now I've fixed Config file path problem.
