### ISSUE TITLE
Netflow Trends?

### ISSUE THREAD

**Issue by Beeez** [javadmohebbi/nfCollector#14]
I see that the recommended configuration on the DB is a 10 day retention - but is there anything employed or plans to include over-time Netflow trends past the 10 days retention?

**Comment by javadmohebbi** [comment]
Hi @Beeez 

Actually when I have started this project as a personal project but now this tool have many users. So I have plan to redesign and re-develop it again for longer period of time using InfluxDB and another database for more days as well as a simple Web GUI  for management.
