### ISSUE TITLE
Resolve IPs (Reverse DNS) [enhancement] [feature request]

### ISSUE THREAD

**Issue by rafaelreis-r** [javadmohebbi/nfCollector#15]
This is an incredible tool! Thanks for your work.

I was able to revive a DD-WRT RFlow / NetFlow function with it, and integrate it to my Grafana home Dashboard. Kudos!

Wondering if we could have the option to enable DNS resolution of the IP adresses before exporting into influxDB, or maybe even have a new optional field into the DB that saves / maps the flow IPs to their DNSses.

**Comment by javadmohebbi** [comment]
Hi @rafaelreis-r, 

Thanks for the feedback. I am planning to redevelop the tool and add more feature to it. But currently I am busy with another project. DNS resolution might be one of the next features.
