### ISSUE TITLE
How to compile for others architecture (ARM)

### ISSUE THREAD

**Issue by jns-fr** [javadmohebbi/nfCollector#17]
Hi

First of all god job for the amazing work. I would like run nfCollector on rapsberry but i don't know how to.
Could you please help me to compile your work for arm architecture?

Thanks in advance

**Comment by javadmohebbi** [comment]
Hi jns-fr

check this [link](https://gist.github.com/conoro/4fca191fad018b6e47922a21fab499ca) to know how you can compile any go application for ARM architecture

Kind regards
