### ISSUE TITLE
Is there support for SSL?

### ISSUE THREAD

**Issue by rodrigocastrillon** [javadmohebbi/nfCollector#19]
Hello. 

Are there plans for using the InfluxDB API with SSL (https/443)?

**Comment by javadmohebbi** [comment]
> Hello.
> 
> Are there plans for using the InfluxDB API with SSL (https/443)?

Hi, @rodrigocastrillon 

I am releasing new version which you can find it [here](https://openintelligence24.com/). I will keep this new version update. Also I will PUT SSL in our wishlist to support it soon

**Comment by javadmohebbi** [comment]
> > Hello.
> > Are there plans for using the InfluxDB API with SSL (https/443)?
> 
> Hi, @rodrigocastrillon
> 
> I am releasing new version which you can find it [here](https://openintelligence24.com/). I will keep this new version update. Also I will PUT SSL in our wishlist to support it soon

Also I will transfer this to new Repository https://github.com/javadmohebbi/goNfCollector
