### ISSUE TITLE
nfcol-dump: Can not decode  EOF

### ISSUE THREAD

**Issue by alagoutte** [javadmohebbi/nfCollector#2]
Hi,

I try to send flow from VMware DVS (ipfix/netflow v10) or HP Comware switch (sflow) and i get always :
`Can not decode  EOF` with nfcol-dump

Do you have a idea ?

**Comment by javadmohebbi** [comment]
Hi @alagoutte 

This package using RFC7011 to decode IPFIX (v10) Netflow Traffics [https://tools.ietf.org/html/rfc7011#section-3 ](https://tools.ietf.org/html/rfc7011#section-3)
If it could not decode it, it wont process it and log the error (in this case End Of File error) to standard output.

Another possible issue is, once the service started, It might get incomplete packets from DVS and after some seconds the problem might resolved.
