### ISSUE TITLE
decoder error: EOF

### ISSUE THREAD

**Issue by alexsuslin** [javadmohebbi/nfCollector#3]
CISCO ASA  9.12(2)9 

lots of

2020/01/30 06:25:00 decoder error: EOF
2020/01/30 06:25:00 decoder error: EOF
2020/01/30 06:25:00 decoder error: EOF
2020/01/30 06:25:00 decoder error: EOF
2020/01/30 06:25:00 decoder error: EOF
2020/01/30 06:25:01 decoder error: EOF
2020/01/30 06:25:01 decoder error: EOF
2020/01/30 06:25:01 decoder error: EOF
2020/01/30 06:25:01 decoder error: EOF

**Comment by javadmohebbi** [comment]
Hi @alexsuslin, nfcol is using [https://godoc.org/github.com/tehmaze/netflow](https://godoc.org/github.com/tehmaze/netflow) to decode & extract flow traffic. When it could not decode flow traffics, it will log it to the output. 

Please let me know what is the version of your Netflow Traffics to fix your issue!

**Comment by alexsuslin** [comment]
sorry, how can I check that?

**Comment by javadmohebbi** [comment]
> sorry, how can I check that?

Actually you must know! You can google how to reconfigure it again. But for your information this app supports 1, 5, 6, 7, 9 & IPFIX (10) versions and SFLOW is not supported.

**Comment by alexsuslin** [comment]
sorry I understood your question wrong, if you were asking about netflow version my cisco device produce it is ver 9 (according to documentation: https://www.cisco.com/c/en/us/td/docs/security/asa/special/netflow/guide/asa_netflow.html)

**Comment by javadmohebbi** [comment]
As I mentioned before, nfcol is using [https://godoc.org/github.com/tehmaze/netflow](https://godoc.org/github.com/tehmaze/netflow) to decode & extract flow traffic. According to the link you have provided, You have configured Netflow Version 9 (RFC 3954) & this app supports this version. I think there might be a problem in CISCO configuration. 

Could you provide a FLOW sample which I can reproduce your problem ?

**Comment by henro4niger** [comment]
Having the same issues, used V5, V9 and IPFIX on my mikrotik machine
2020/02/13 13:35:42 Can not decode  EOF
2020/02/13 13:35:42 Can not decode  EOF
2020/02/13 13:35:42 Can not decode  EOF
2020/02/13 13:35:43 Can not decode  EOF
2020/02/13 13:35:43 Can not decode  EOF
2020/02/13 13:35:43 Can not decode  EOF
2020/02/13 13:35:43 Can not decode  EOF
2020/02/13 13:35:43 Can not decode  EOF
2020/02/13 13:35:43 Can not decode  EOF
2020/02/13 13:35:43 Can not decode  EOF
2020/02/13 13:35:43 Can not decode  EOF
2020/02/13 13:35:43 Can not decode  EOF
2020/02/13 13:35:43 Can not decode  EOF

**Comment by javadmohebbi** [comment]
> Having the same issues, used V5, V9 and IPFIX on my mikrotik machine
> 2020/02/13 13:35:42 Can not decode EOF
> 2020/02/13 13:35:42 Can not decode EOF
> 2020/02/13 13:35:42 Can not decode EOF
> 2020/02/13 13:35:43 Can not decode EOF
> 2020/02/13 13:35:43 Can not decode EOF
> 2020/02/13 13:35:43 Can not decode EOF
> 2020/02/13 13:35:43 Can not decode EOF
> 2020/02/13 13:35:43 Can not decode EOF
> 2020/02/13 13:35:43 Can not decode EOF
> 2020/02/13 13:35:43 Can not decode EOF
> 2020/02/13 13:35:43 Can not decode EOF
> 2020/02/13 13:35:43 Can not decode EOF
> 2020/02/13 13:35:43 Can not decode EOF

Does it happen all the time or just for some seconds ? Because after  **nfcol** receives completed netflow records it must be fixed.
