### ISSUE TITLE
Crash in Windows

### ISSUE THREAD

**Issue by danfoxley** [javadmohebbi/nfCollector#6]
Any thoughts?  Seems two separate issues ( IP2Location and panic at bottom)
----------------Console Output

C:\Program Files\Netflow-Collector>nfcol.exe
2020/03/30 16:22:15 Server is listening on 0.0.0.0:6859
2020/03/30 16:22:15 Export job started
2020/03/30 16:22:15 IP2Location Error:  exec: "": executable file not found in %
PATH%
2020/03/30 16:22:16 IP2Location Error:  exec: "": executable file not found in %
PATH%
2020/03/30 16:22:16 IP2Location Error:  exec: "": executable file not found in %
PATH%

2020/03/30 16:23:05 IP2Location Error:  exec: "": executable file not found in %
PATH%
2020/03/30 16:23:05 IP2Location Error:  exec: "": executable file not found in %
PATH%
2020/03/30 16:23:05 IP2Location Error:  exec: "": executable file not found in %
PATH%
2020/03/30 16:23:05 IP2Location Error:  exec: "": executable file not found in %
PATH%
2020/03/30 16:23:05 IP2Location Error:  exec: "": executable file not found in %
PATH%
2020/03/30 16:23:05 IP2Location Error:  exec: "": executable file not found in %
PATH%
2020/03/30 16:23:05 IP2Location Error:  exec: "": executable file not found in %
PATH%
2020/03/30 16:23:05 IP2Location Error:  exec: "": executable file not found in %
PATH%
2020/03/30 16:23:05 IP2Location Error:  exec: "": executable file not found in %
PATH%
2020/03/30 16:23:05 IP2Location Error:  exec: "": executable file not found in %
PATH%
2020/03/30 16:23:05 Job for measurement () Started!
2020/03/30 16:23:05 Deleting .done extension & rewrite suspended .working files
in directory:  C:\Users\danf\AppData\Local\Temp\
2020/03/30 16:23:05 IP2Location Error:  exec: "": executable file not found in %
PATH%
2020/03/30 16:23:05 IP2Location Error:  exec: "": executable file not found in %
PATH%
2020/03/30 16:23:05 IP2Location Error:  exec: "": executable file not found in %
PATH%
2020/03/30 16:23:05 IP2Location Error:  exec: "": executable file not found in %
PATH%
2020/03/30 16:23:05 IP2Location Error:  exec: "": executable file not found in %
PATH%
2020/03/30 16:23:05 IP2Location Error:  exec: "": executable file not found in %
PATH%
2020/03/30 16:23:05 IP2Location Error:  exec: "": executable file not found in %
PATH%
2020/03/30 16:23:05 IP2Location Error:  exec: "": executable file not found in %
PATH%
2020/03/30 16:23:05 IP2Location Error:  exec: "": executable file not found in %
PATH%
2020/03/30 16:23:05 IP2Location Error:  exec: "": executable file not found in %
PATH%
2020/03/30 16:23:05 IP2Location Error:  exec: "": executable file not found in %
PATH%
2020/03/30 16:23:05 IP2Location Error:  exec: "": executable file not found in %
PATH%
2020/03/30 16:23:05 Job for measurement (sum_proto) Started!
2020/03/30 16:23:05 Deleting .done extension & rewrite suspended .working files
in directory:  C:\Users\danf\AppData\Local\Tempsum_proto\
2020/03/30 16:23:05 IP2Location Error:  exec: "": executable file not found in %
PATH%
2020/03/30 16:23:05 File nfc-20200330-16-15-(sum_proto).metrics.working renamed
to nfc-20200330-16-15-(sum_proto).metrics
2020/03/30 16:23:05 IP2Location Error:  exec: "": executable file not found in %
PATH%
2020/03/30 16:23:05 IP2Location Error:  exec: "": executable file not found in %
PATH%
2020/03/30 16:23:05 IP2Location Error:  exec: "": executable file not found in %
PATH%
2020/03/30 16:23:05 File nfc-20200330-16-16-(sum_proto).metrics.working renamed
to nfc-20200330-16-16-(sum_proto).metrics
2020/03/30 16:23:05 IP2Location Error:  exec: "": executable file not found in %
PATH%
2020/03/30 16:23:05 IP2Location Error:  exec: "": executable file not found in %
PATH%
2020/03/30 16:23:05 IP2Location Error:  exec: "": executable file not found in %
PATH%
2020/03/30 16:23:05 IP2Location Error:  exec: "": executable file not found in %
PATH%
2020/03/30 16:23:05 IP2Location Error:  exec: "": executable file not found in %
PATH%
2020/03/30 16:23:05 IP2Location Error:  exec: "": executable file not found in %
PATH%
2020/03/30 16:23:06 File nfc-20200330-16-17-(sum_proto).metrics.working renamed
to nfc-20200330-16-17-(sum_proto).metrics
2020/03/30 16:23:06 IP2Location Error:  exec: "": executable file not found in %
PATH%
2020/03/30 16:23:06 IP2Location Error:  exec: "": executable file not found in %
PATH%
2020/03/30 16:23:06 IP2Location Error:  exec: "": executable file not found in %
PATH%
2020/03/30 16:23:06 IP2Location Error:  exec: "": executable file not found in %
PATH%
2020/03/30 16:23:06 IP2Location Error:  exec: "": executable file not found in %
PATH%
2020/03/30 16:23:06 IP2Location Error:  exec: "": executable file not found in %
PATH%
2020/03/30 16:23:06 IP2Location Error:  exec: "": executable file not found in %
PATH%
2020/03/30 16:23:06 IP2Location Error:  exec: "": executable file not found in %
PATH%
2020/03/30 16:23:06 IP2Location Error:  exec: "": executable file not found in %
PATH%
2020/03/30 16:23:06 IP2Location Error:  exec: "": executable file not found in %
PATH%
2020/03/30 16:23:06 IP2Location Error:  exec: "": executable file not found in %
PATH%
2020/03/30 16:23:06 IP2Location Error:  exec: "": executable file not found in %
PATH%
2020/03/30 16:23:06 IP2Location Error:  exec: "": executable file not found in %
PATH%
2020/03/30 16:23:06 IP2Location Error:  exec: "": executable file not found in %
PATH%
2020/03/30 16:23:06 IP2Location Error:  exec: "": executable file not found in %
PATH%
2020/03/30 16:23:06 IP2Location Error:  exec: "": executable file not found in %
PATH%
2020/03/30 16:23:06 IP2Location Error:  exec: "": executable file not found in %
PATH%
2020/03/30 16:23:06 IP2Location Error:  exec: "": executable file not found in %
PATH%
2020/03/30 16:23:07 IP2Location Error:  exec: "": executable file not found in %
PATH%
2020/03/30 16:23:07 IP2Location Error:  exec: "": executable file not found in %
PATH%
2020/03/30 16:23:07 IP2Location Error:  exec: "": executable file not found in %
PATH%
2020/03/30 16:23:07 IP2Location Error:  exec: "": executable file not found in %
PATH%
2020/03/30 16:23:07 Reading directory C:\Users\danf\AppData\Local\Temp\
2020/03/30 16:23:07 Job for measurement () Finished!
panic: runtime error: index out of range [3] with length 1

goroutine 211 [running]:
nfCollector/pkg/job.(*Job).WriteToDb(0xc00014a1a0, 0x0, 0x0)
        /home/mj/go/src/nfCollector/pkg/job/job.go:145 +0x1fcd
created by nfCollector/pkg/job.(*Job).Run.func1
        /home/mj/go/src/nfCollector/pkg/job/job.go:85 +0x332

C:\Program Files\Netflow-Collector>

**Comment by javadmohebbi** [comment]
Hi @danfoxley 
Did you set the correct path of IP2Location binary in `nfc.yaml` file ?

Please read the guide of IP2location [here](https://github.com/javadmohebbi/IP2Location) & download the Windows version & set the correct path for IP2Location in `nfc.yaml` file. 

Hope your problem fixed

Best regards
