### ISSUE TITLE
Debian Package Journactl Output - Panic

### ISSUE THREAD

**Issue by danfoxley** [javadmohebbi/nfCollector#7]
Mar 31 14:31:27  nfcol[57471]: panic: runtime error: invalid memory address or nil pointer dereference
Mar 31 14:31:27  nfcol[57471]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x45d977]
Mar 31 14:31:27  nfcol[57471]: goroutine 856794 [running]:
Mar 31 14:31:27  nfcol[57471]: fmt.(*buffer).writeString(...)
Mar 31 14:31:27  nfcol[57471]:         /usr/lib/go-1.13/src/fmt/print.go:82
Mar 31 14:31:27  nfcol[57471]: fmt.(*fmt).padString(0xc001462520, 0x0, 0x13)
Mar 31 14:31:27  nfcol[57471]:         /usr/lib/go-1.13/src/fmt/format.go:110 +0x8c
Mar 31 14:31:27  nfcol[57471]: fmt.(*fmt).fmtS(0xc001462520, 0x0, 0x13)
Mar 31 14:31:27  nfcol[57471]:         /usr/lib/go-1.13/src/fmt/format.go:359 +0x61
Mar 31 14:31:27  nfcol[57471]: fmt.(*pp).fmtString(0xc0014624e0, 0x0, 0x13, 0x76)
Mar 31 14:31:27  nfcol[57471]:         /usr/lib/go-1.13/src/fmt/print.go:447 +0x131
Mar 31 14:31:27  nfcol[57471]: fmt.(*pp).printArg(0xc0014624e0, 0x8ea300, 0xc0010dc750, 0x76)
Mar 31 14:31:27  nfcol[57471]:         /usr/lib/go-1.13/src/fmt/print.go:698 +0x877
Mar 31 14:31:27  nfcol[57471]: fmt.(*pp).doPrintln(0xc0014624e0, 0xc0010c85a8, 0x2, 0x2)
Mar 31 14:31:27  nfcol[57471]:         /usr/lib/go-1.13/src/fmt/print.go:1173 +0xb2
Mar 31 14:31:27  nfcol[57471]: fmt.Sprintln(0xc0010c85a8, 0x2, 0x2, 0x8ea0c0, 0x1)
Mar 31 14:31:27  nfcol[57471]:         /usr/lib/go-1.13/src/fmt/print.go:281 +0x52
Mar 31 14:31:27  nfcol[57471]: log.(*Logger).Println(0xc0000b21e0, 0xc0010c85a8, 0x2, 0x2)
Mar 31 14:31:27  nfcol[57471]:         /usr/lib/go-1.13/src/log/log.go:188 +0x3f
Mar 31 14:31:27  nfcol[57471]: github.com/spf13/viper.(*Viper).ReadInConfig(0xc0000be200, 0xc00105f680, 0xb)
Mar 31 14:31:27  nfcol[57471]:         /home/mj/go/src/github.com/spf13/viper/viper.go:1253 +0x19b
Mar 31 14:31:27  nfcol[57471]: github.com/spf13/viper.ReadInConfig(...)
Mar 31 14:31:27  nfcol[57471]:         /home/mj/go/src/github.com/spf13/viper/viper.go:1241
Mar 31 14:31:27  nfcol[57471]: nfCollector/pkg/cnf.ReadConfig(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
Mar 31 14:31:27  nfcol[57471]:         /home/mj/go/src/nfCollector/pkg/cnf/cnf.go:82 +0x145
Mar 31 14:31:27  nfcol[57471]: nfCollector/pkg/exporter/influx.WriteSummaryProtoGeo(0x0, 0x0, 0x0, 0x160180ea29283bc1)
Mar 31 14:31:27  nfcol[57471]:         /home/mj/go/src/nfCollector/pkg/exporter/influx/influx.go:51 +0x4d
Mar 31 14:31:27  nfcol[57471]: nfCollector/pkg/exporter/influx.Write(0x0, 0x0, 0x0)
Mar 31 14:31:27  nfcol[57471]:         /home/mj/go/src/nfCollector/pkg/exporter/influx/influx.go:27 +0xc9
Mar 31 14:31:27  nfcol[57471]: nfCollector/pkg/exporter.ExportToInflux(...)
Mar 31 14:31:27  nfcol[57471]:         /home/mj/go/src/nfCollector/pkg/exporter/exporter.go:32
Mar 31 14:31:27  nfcol[57471]: nfCollector/pkg/exporter.Write(0x0, 0x0, 0x0)
Mar 31 14:31:27  nfcol[57471]:         /home/mj/go/src/nfCollector/pkg/exporter/exporter.go:21 +0xf9
Mar 31 14:31:27  nfcol[57471]: nfCollector/pkg/service.(*Service).checkPacket(0xc00019d080, 0x90cec0, 0xc000deefc0, 0xa58ce0, 0xc000d05ec0, 0x0, 0xc000014500, 0x2300, 0x2300, 0x1)
Mar 31 14:31:27  nfcol[57471]:         /home/mj/go/src/nfCollector/pkg/service/service.go:138 +0x3c3
Mar 31 14:31:27  nfcol[57471]: created by nfCollector/pkg/service.(*Service).Serve
Mar 31 14:31:27  nfcol[57471]:         /home/mj/go/src/nfCollector/pkg/service/service.go:91 +0x418
Mar 31 14:31:27  systemd[1]: nfcol.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Mar 31 14:31:27  systemd[1]: nfcol.service: Unit entered failed state.

**Comment by javadmohebbi** [comment]
Hi @danfoxley 

Thank you for submitting issue here. 

- What's the output of `$ uname -a` ?
- What's the output of `$ pkg -l | grep -i nfcol` ?
- Share your `nfc.yaml` configuration from this path `/etc/nfcol/nfc.yaml`
