### ISSUE TITLE
Getting 'invalid precision' error from influxdb

### ISSUE THREAD

**Issue by uselessjargon** [javadmohebbi/nfCollector#8]
Hi, I'm using influxdb 1.8.0, I have netflows going to nfcol and can see them with nfcol-dump (as well as stdout). When I enable the exporter process to push the data to influxdb I get the below precision error. 

```
[root@XXXXX influxdb]# /usr/local/bin/nfcol -debug true
2020/04/29 22:54:13 Server is listening on [::]:6859
2020/04/29 22:54:13 Export job started
2020/04/29 22:54:32 decoder error: EOF
2020/04/29 22:55:03 decoder error: EOF
2020/04/29 22:55:04 Export job configs to send metrics to InfluxDB: 127.0.0.1:8086 (Database: netflowDB)
2020/04/29 22:55:04 Job for measurement (sum_proto) Started!
2020/04/29 22:55:04 Deleting .done extension & rewrite suspended .working files in directory:  /tmp/nfcol/sum_proto/
2020/04/29 22:55:04 Job for measurement (sum_proto_geo) Started!
2020/04/29 22:55:04 Deleting .done extension & rewrite suspended .working files in directory:  /tmp/nfcol/sum_proto_geo/
2020/04/29 22:55:06 Reading directory /tmp/nfcol/sum_proto_geo/
2020/04/29 22:55:06 Reading directory /tmp/nfcol/sum_proto/
2020/04/29 22:55:06 Error: {"error":"invalid precision \"us\" (use n, u, ms, s, m or h)"}
```

The influxdb request log shows this as the last lines sent:
```
127.0.0.1 - - [29/Apr/2020:22:49:06 +0000] "POST /write?consistency=&db=netflowDB&precision=us&rp= HTTP/1.1" 400 63 "-" "InfluxDBClient" a1464ea6-8a6b-11ea-8013-005056a0ffa6 196
127.0.0.1 - - [29/Apr/2020:22:49:06 +0000] "POST /write?consistency=&db=netflowDB&precision=us&rp= HTTP/1.1" 400 63 "-" "InfluxDBClient" a1465fa2-8a6b-11ea-8014-005056a0ffa6 50
127.0.0.1 - - [29/Apr/2020:22:51:06 +0000] "POST /write?consistency=&db=netflowDB&precision=us&rp= HTTP/1.1" 400 63 "-" "InfluxDBClient" e8ccd35e-8a6b-11ea-8015-005056a0ffa6 191
127.0.0.1 - - [29/Apr/2020:22:51:06 +0000] "POST /write?consistency=&db=netflowDB&precision=us&rp= HTTP/1.1" 400 63 "-" "InfluxDBClient" e8cce10b-8a6b-11ea-8016-005056a0ffa6 53
```

Thanks for any help you can provide

**Comment by AcroTiger** [comment]
I am getting this same error @uselessjargon, did you ever figure this out?

**Comment by AcroTiger** [comment]
After some research it looks like the Go module is appending a *"us"* for *"microseconds"* after the time signature in the *unixNano* function (maybe?) in the *influx.go* module in **pkg/exporter/influx/**

@uselessjargon You wouldn't know how to fix this, would you?

**Comment by uselessjargon** [comment]
@AcroTiger I do see a 'Precision: "us"' in ./pkg/job/job.go but maybe yours suggestion is where it's coming from.  I'll look. 

Line 197 of pkg/job/job.go
```
	bp, _ := client.NewBatchPoints(client.BatchPointsConfig{
		Database:  conf.InfluxDB.Database,
		Precision: "us",
	})
```

According to this link https://docs.influxdata.com/influxdb/v1.6/troubleshooting/frequently-asked-questions/#why-does-influxdb-fail-to-parse-microsecond-units-in-the-configuration-file a "us" is only valid in the config file, not the API. 

Fwiw, I tried updating the job.go with a 'u' and recompiled but got errors on missing 'github.com/influxdata/influxdb/client/v2' lib since the location to the lib in influxdb repo was changed. I got past my compiling issue by using 'github.com/influxdata/influxdb1-client/v2' instead (solution found from another issue) but now I get the below error on the recompiled program. I'm a Go newb so it's slow going.

```
Apr 30 17:26:06 z10116 nfcol[33264]: goroutine 24 [running]:
Apr 30 17:26:06 z10116 nfcol[33264]: github.com/influxdata/influxdb1-client/v2.(*client).Write(0xc000234000, 0x0, 0x0, 0x0, 0x0)
Apr 30 17:26:06 z10116 nfcol[33264]: /root/go/src/github.com/influxdata/influxdb1-client/v2/client.go:369 +0x72
Apr 30 17:26:06 z10116 nfcol[33264]: nfCollector/pkg/job.(*Job).WriteToDb(0xc00019a1c0, 0xc0001c6260, 0x9)
Apr 30 17:26:06 z10116 nfcol[33264]: /root/go/src/nfCollector/pkg/job/job.go:253 +0x10dc
Apr 30 17:26:06 z10116 nfcol[33264]: created by nfCollector/pkg/job.(*Job).Run.func1
Apr 30 17:26:06 z10116 nfcol[33264]: /root/go/src/nfCollector/pkg/job/job.go:85 +0x30c
```

**Comment by uselessjargon** [comment]
@AcroTiger I've got it working after commenting out the 'Precision: "us"' line in job.go and recompiling with the updated influxdb client path. I tried changing the 'us' to 'u' but that caused my job.go stracktrace in my previous comment above. 

By removing the Precision line, the client defaults back to ns. Not sure what the impact of using 'ns' is but my dashboards are now showing data now. Let me know if you need help on compiling. It was somewhat of a kludge for me.

**Comment by AcroTiger** [comment]
@uselessjargon Woot! I'll give it a shot, but I also am NOT a **Go** guy. I'll most likely struggle and learn a lot. LoL Don't suppose you happen to be on Discord?

**Comment by javadmohebbi** [comment]
> @AcroTiger I've got it working after commenting out the 'Precision: "us"' line in job.go and recompiling with the updated influxdb client path. I tried changing the 'us' to 'u' but that caused my job.go stracktrace in my previous comment above.
> 
> By removing the Precision line, the client defaults back to ns. Not sure what the impact of using 'ns' is but my dashboards are now showing data now. Let me know if you need help on compiling. It was somewhat of a kludge for me.

Hi There,
Since I have tested nfcol on InfluxDB 1.7, Data was showing in dashboard correctly. I will make a change to `job.go`  file to fix the problem that you have faced. 

Today I will update the repo with the change that you suggest.

Thank you @uselessjargon

**Comment by javadmohebbi** [comment]
Hi @AcroTiger and @uselessjargon 

Code, Binaries and deb package has updated!

Kind regards
