### ISSUE TITLE
Decoder Error: EOF

### ISSUE THREAD

**Issue by bile0026** [javadmohebbi/nfCollector#9]
Running on Ubuntu 20.04 LTS, running nfcol-dump shows output coming in, but it doesn't appear to be writing to influxDB. Getting this error in the service status. Is there another log somewhere? I don't see anything in /var/log. Installed via binaries. 

```
● nfcol.service - Netflow Collector is a tool that collect Netflow v1, v5, v9 & IPFIX and export them in many databases like InfluxDB
     Loaded: loaded (/lib/systemd/system/nfcol.service; enabled; vendor preset: enabled)
     Active: active (running) since Mon 2020-06-15 10:38:51 CDT; 2min 35s ago
       Docs: https://mjmohebbi.com
   Main PID: 5993 (nfcol)
      Tasks: 10 (limit: 4557)
     Memory: 32.8M
     CGroup: /system.slice/nfcol.service
             └─5993 /usr/local/bin/nfcol

Jun 15 10:40:04 blueflow nfcol[5993]: 2020/06/15 10:40:04 decoder error: EOF
Jun 15 10:40:16 blueflow nfcol[5993]: 2020/06/15 10:40:16 decoder error: EOF
Jun 15 10:40:21 blueflow nfcol[5993]: 2020/06/15 10:40:21 decoder error: EOF
Jun 15 10:40:21 blueflow nfcol[5993]: 2020/06/15 10:40:21 decoder error: EOF
Jun 15 10:40:37 blueflow nfcol[5993]: 2020/06/15 10:40:37 decoder error: EOF
Jun 15 10:40:38 blueflow nfcol[5993]: 2020/06/15 10:40:38 decoder error: EOF
Jun 15 10:40:51 blueflow nfcol[5993]: 2020/06/15 10:40:51 decoder error: EOF
Jun 15 10:40:57 blueflow nfcol[5993]: 2020/06/15 10:40:57 decoder error: EOF
Jun 15 10:41:11 blueflow nfcol[5993]: 2020/06/15 10:41:11 decoder error: EOF
Jun 15 10:41:17 blueflow nfcol[5993]: 2020/06/15 10:41:17 decoder error: EOF
```

```
# # # # # # # # # # # # # # # # # #
#       Netflow Collector         #
#         Configuration           #
# # # # # # # # # # # # # # # # # #
server:
  # Listen Address
  address: 0.0.0.0

  # Listen UDP Port
  port: 6859

  # If true, nfc will write flow data into stdout
  dump: false

  # Activate forwarder
  forwarder: true

  # Host to forward - Can be separated by ; (semi-colon) eg: 127.0.0.1;192.168.100.1
  forwarderHost: 127.0.0.1

  # Forwarder UDP Port
  forwarderPort: 7161

# # # # # # # # # # # # # # # # # #
#    IP2Location Configuration    #
# # # # # # # # # # # # # # # # # #
ip2location:
  # IP2Location command path
  cmd: /usr/local/bin/ip2location

  # Path to Local GEO Database. Read more at:
  #      https://github.com/javadmohebbi/IP2Location#local-database-format
  local: /etc/ip2location/local.csv

# # # # # # # # # # # # # # # # # #
#     Exporter Configuration      #
# # # # # # # # # # # # # # # # # #
exporter:
  # Enable if it's true
  enable: false

  # Currently Only InfluxDB (1.x) supported
  type: influxdb


# # # # # # # # # # # # # # # # # #
#     InfluxDB Configuration      #
# # # # # # # # # # # # # # # # # #
influxDB:
  # InfluxDB Host
  host: 127.0.0.1

  # InfluxDB Port
  port: 8086

  # InfluxDB Username. Can be null
  username: netflow

  # InfluxDB Password. Can be null
  password: <password>
  # InfluxDB Database
  # InfluxDB command example for creating database:
  #       CREATE DATABASE "netflowDB" WITH DURATION 10d REPLICATION 1 SHARD DURATION 1h NAME "nfc"
  database: netflow

  # Temp Dir for InfluxDB Metrics. MUST be ended with / (Linux) or \ (Windows)
  tmpDir: /tmp/nfcol/


# # # # # # # # # # # # # # # # # #
#          Measurements           #
# # # # # # # # # # # # # # # # # #
measurements:
  # Netflow Summary Measurement Name
  summaryProto: sum_proto

  # Netflow GEO Summary Measurement Name
  summaryProtoGeo: sum_proto_geo
```

**Comment by egarnel** [comment]
I am seeing the same error in 18.04 LTS.  /tmp/nfcol is empty too

**Comment by javadmohebbi** [comment]
> Running on Ubuntu 20.04 LTS, running nfcol-dump shows output coming in, but it doesn't appear to be writing to influxDB. Getting this error in the service status. Is there another log somewhere? I don't see anything in /var/log. Installed via binaries.
> 
> ```
> ● nfcol.service - Netflow Collector is a tool that collect Netflow v1, v5, v9 & IPFIX and export them in many databases like InfluxDB
>      Loaded: loaded (/lib/systemd/system/nfcol.service; enabled; vendor preset: enabled)
>      Active: active (running) since Mon 2020-06-15 10:38:51 CDT; 2min 35s ago
>        Docs: https://mjmohebbi.com
>    Main PID: 5993 (nfcol)
>       Tasks: 10 (limit: 4557)
>      Memory: 32.8M
>      CGroup: /system.slice/nfcol.service
>              └─5993 /usr/local/bin/nfcol
> 
> Jun 15 10:40:04 blueflow nfcol[5993]: 2020/06/15 10:40:04 decoder error: EOF
> Jun 15 10:40:16 blueflow nfcol[5993]: 2020/06/15 10:40:16 decoder error: EOF
> Jun 15 10:40:21 blueflow nfcol[5993]: 2020/06/15 10:40:21 decoder error: EOF
> Jun 15 10:40:21 blueflow nfcol[5993]: 2020/06/15 10:40:21 decoder error: EOF
> Jun 15 10:40:37 blueflow nfcol[5993]: 2020/06/15 10:40:37 decoder error: EOF
> Jun 15 10:40:38 blueflow nfcol[5993]: 2020/06/15 10:40:38 decoder error: EOF
> Jun 15 10:40:51 blueflow nfcol[5993]: 2020/06/15 10:40:51 decoder error: EOF
> Jun 15 10:40:57 blueflow nfcol[5993]: 2020/06/15 10:40:57 decoder error: EOF
> Jun 15 10:41:11 blueflow nfcol[5993]: 2020/06/15 10:41:11 decoder error: EOF
> Jun 15 10:41:17 blueflow nfcol[5993]: 2020/06/15 10:41:17 decoder error: EOF
> ```
> 
> ```
> # # # # # # # # # # # # # # # # # #
> #       Netflow Collector         #
> #         Configuration           #
> # # # # # # # # # # # # # # # # # #
> server:
>   # Listen Address
>   address: 0.0.0.0
> 
>   # Listen UDP Port
>   port: 6859
> 
>   # If true, nfc will write flow data into stdout
>   **dump: false**
> 
>   # Activate forwarder
>   forwarder: true
> 
>   # Host to forward - Can be separated by ; (semi-colon) eg: 127.0.0.1;192.168.100.1
>   forwarderHost: 127.0.0.1
> 
>   # Forwarder UDP Port
>   forwarderPort: 7161
> 
> # # # # # # # # # # # # # # # # # #
> #    IP2Location Configuration    #
> # # # # # # # # # # # # # # # # # #
> ip2location:
>   # IP2Location command path
>   cmd: /usr/local/bin/ip2location
> 
>   # Path to Local GEO Database. Read more at:
>   #      https://github.com/javadmohebbi/IP2Location#local-database-format
>   local: /etc/ip2location/local.csv
> 
> # # # # # # # # # # # # # # # # # #
> #     Exporter Configuration      #
> # # # # # # # # # # # # # # # # # #
> exporter:
>   # Enable if it's true
>   **enable: false**
> 
>   # Currently Only InfluxDB (1.x) supported
>   type: influxdb
> 
> 
> # # # # # # # # # # # # # # # # # #
> #     InfluxDB Configuration      #
> # # # # # # # # # # # # # # # # # #
> influxDB:
>   # InfluxDB Host
>   host: 127.0.0.1
> 
>   # InfluxDB Port
>   port: 8086
> 
>   # InfluxDB Username. Can be null
>   username: netflow
> 
>   # InfluxDB Password. Can be null
>   password: <password>
>   # InfluxDB Database
>   # InfluxDB command example for creating database:
>   #       CREATE DATABASE "netflowDB" WITH DURATION 10d REPLICATION 1 SHARD DURATION 1h NAME "nfc"
>   database: netflow
> 
>   # Temp Dir for InfluxDB Metrics. MUST be ended with / (Linux) or \ (Windows)
>   tmpDir: /tmp/nfcol/
> 
> 
> # # # # # # # # # # # # # # # # # #
> #          Measurements           #
> # # # # # # # # # # # # # # # # # #
> measurements:
>   # Netflow Summary Measurement Name
>   summaryProto: sum_proto
> 
>   # Netflow GEO Summary Measurement Name
>   summaryProtoGeo: sum_proto_geo
> ```

Hi @bile002 & @egarnel 

In `/etc/nfcol/nfc.yaml` be sure that `dump: false` and **exporter** is enabled 
```
server:

     ....

     dump: false

     ....

exporter: 
      enabled: true

      ....

```

Also To check logs regarding the `nfcol` service you can see `/var/log/syslog`.
`decoder error: EOF` error might happen if `nfcol` fails to decode the flows. 

So please provide me more information to understand & fix the problem:
- What is your Netflow version?
- What is your InfluxDB version?
- Provide the output of command `cat /var/log/syslog | grep nfcol`
- And `ls /tmp/nfcol/sum_proto -la` , `ls /tmp/nfcol/sum_proto _geo -la`

**Comment by bile0026** [comment]
> Hi @bile002 & @egarnel
> 
> In `/etc/nfcol/nfc.yaml` be sure that `dump: false` and **exporter** is enabled
> 
> ```
> server:
> 
>      ....
> 
>      dump: false
> 
>      ....
> 
> exporter: 
>       enabled: true
> 
>       ....
> ```
> 
> Also To check logs regarding the `nfcol` service you can see `/var/log/syslog`.
> `decoder error: EOF` error might happen if `nfcol` fails to decode the flows.
> 
> So please provide me more information to understand & fix the problem:
> 
> * What is your Netflow version?
> * What is your InfluxDB version?
> * Provide the output of command `cat /var/log/syslog | grep nfcol`
> * And `ls /tmp/nfcol/sum_proto -la` , `ls /tmp/nfcol/sum_proto _geo -la`


@javadmohebbi 
Well looks like it was the exporter not being enabled. I have flow data coming in now. I included the outputs anyways for reference of what this would look like if someone else experiences the same issue. Thank you for the clarification! Very nice product. 

* Netflow v9
* InfluxDB version 1.8.0-1

# /var/log/syslog
```
Jun 20 08:06:39 blueflow nfcol[9956]: 2020/06/20 08:06:39 decoder error: EOF
Jun 20 08:06:56 blueflow nfcol[9956]: 2020/06/20 08:06:56 decoder error: EOF
Jun 20 08:07:07 blueflow nfcol[9956]: 2020/06/20 08:07:07 decoder error: EOF
Jun 20 08:07:18 blueflow nfcol[9956]: 2020/06/20 08:07:18 decoder error: EOF
Jun 20 08:07:28 blueflow nfcol[9956]: 2020/06/20 08:07:28 decoder error: EOF
Jun 20 08:07:37 blueflow nfcol[9956]: 2020/06/20 08:07:37 decoder error: EOF
Jun 20 08:07:46 blueflow nfcol[9956]: 2020/06/20 08:07:46 decoder error: EOF
Jun 20 08:07:53 blueflow nfcol[9956]: 2020/06/20 08:07:53 decoder error: EOF
Jun 20 08:08:00 blueflow nfcol[9956]: 2020/06/20 08:08:00 decoder error: EOF
Jun 20 08:08:09 blueflow nfcol[9956]: 2020/06/20 08:08:09 decoder error: EOF
Jun 20 08:08:19 blueflow nfcol[9956]: 2020/06/20 08:08:19 decoder error: EOF
Jun 20 08:08:30 blueflow nfcol[9956]: 2020/06/20 08:08:30 decoder error: EOF
Jun 20 08:08:47 blueflow nfcol[9956]: 2020/06/20 08:08:47 decoder error: EOF
Jun 20 08:09:06 blueflow nfcol[9956]: 2020/06/20 08:09:06 decoder error: EOF
Jun 20 08:09:22 blueflow nfcol[9956]: 2020/06/20 08:09:22 decoder error: EOF
Jun 20 08:09:37 blueflow nfcol[9956]: 2020/06/20 08:09:37 decoder error: EOF
Jun 20 08:10:00 blueflow nfcol[9956]: 2020/06/20 08:10:00 decoder error: EOF
Jun 20 08:10:21 blueflow nfcol[9956]: 2020/06/20 08:10:21 decoder error: EOF
Jun 20 08:10:42 blueflow nfcol[9956]: 2020/06/20 08:10:42 decoder error: EOF
Jun 20 08:11:06 blueflow nfcol[9956]: 2020/06/20 08:11:06 decoder error: EOF
Jun 20 08:11:16 blueflow nfcol[9956]: 2020/06/20 08:11:16 decoder error: EOF
Jun 20 08:11:30 blueflow nfcol[9956]: 2020/06/20 08:11:30 decoder error: EOF
Jun 20 08:11:36 blueflow nfcol[9956]: 2020/06/20 08:11:36 decoder error: EOF
Jun 20 08:11:37 blueflow nfcol[9956]: 2020/06/20 08:11:37 decoder error: EOF
Jun 20 08:11:51 blueflow nfcol[9956]: 2020/06/20 08:11:51 decoder error: EOF
Jun 20 08:12:08 blueflow nfcol[9956]: 2020/06/20 08:12:08 decoder error: EOF
Jun 20 08:12:31 blueflow nfcol[9956]: 2020/06/20 08:12:31 decoder error: EOF
Jun 20 08:12:55 blueflow nfcol[9956]: 2020/06/20 08:12:55 decoder error: EOF
```
```ls: cannot access '/tmp/nfcol/sum_proto': No such file or directory```

```ls: cannot access '/tmp/nfcol/sum_proto_geo': No such file or directory```

# ls -lah /tmp/nfcol
```
user@blueflow:~$ ls -lah /tmp/nfcol/
total 8.0K
drwxrwxr-x  2 user user 4.0K Jun 15 10:49 .
drwxrwxrwt 15 root   root   4.0K Jun 20 08:11 ..
```

**Comment by egarnel** [comment]
I had to create the /tmp/nfcol dir and then changing exporter to true made things work. Thanks
